language: python

python:
  - 2.7
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python -m unittest discover elisp

after_success:
  - coverage run -m unittest discover
  - coveralls
